apiVersion: v1
kind: Service
metadata:
  name: custom-validator-as-a-service
  namespace: development
spec:
  ports:
    - name: http
      port: 8081
  type: LoadBalancer
  selector:
    apps: custom-validator-service
